title:              Binary_Sunset
email:              jupitersinsight@protonmail.com
description:        Blog di appunti personali (segreti) di sistemista imperiale
author:             Andrea Calarco
baseurl:            "/"
url:                "https://jupitersinsight.github.io"

# Social Profiles
twitter_username:   
github_username:    jupitersinsight 
facebook_username:  
instagram_username:  
linkedin_username:  ac92

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
